image: node:22-alpine

cache:
  paths:
    - node_modules/
    - .next/cache/

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm i
    - npm run build
    - rm -rf ./public
    - mv ./out ./public
  after_script:
    - rm -rf out
  artifacts:
    paths:
    - public
  only:
    - main
