image: node:latest

cache:
  paths:
    - node_modules/
    - public/
    - .cache/

stages:
  - deploy

pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - mv ./build ./public
  artifacts:
    paths:
    - public
  only:
    - master
